name: Test mongo-arrow

on:
  push:
  pull_request:

jobs:
  test:
    name: Test ${{ matrix.python_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python_version: ['3.6', '3.9']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.4
          mongodb-replica-set: test-rs
      - name: Install libbson
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt-get install libbson-1.0-0 libbson-dev
          elif [ "$RUNNER_OS" == "macOS" ]; then
              sudo brew install mongo-c-driver
          else
              echo "$RUNNER_OS not supported"
              exit 1
          fi
        working-directory: ./bindings/python
      - name: Install Python dependencies
        run: |
          python -m pip install -U pip wheel
          pip install 'cython>=0.29' 'pyarrow>=3' 'numpy>=1.16.6' 'pymongo>=3.11,<4'
          python -c 'import pyarrow as pa; pa.create_library_symlinks()'
        working-directory: ./bindings/python
      - name: Run test suite
        run: |
          CFLAGS=$(pkg-config --cflags libbson-1.0) \
          CXXFLAGS=$(pkg-config --cflags libbson-1.0) \
           LDFLAGS=$(pkg-config --libs libbson-1.0) \
           python setup.py test
        working-directory: ./bindings/python
