name: Test mongo-arrow

on:
  push:
  pull_request:

jobs:
  test:
    name: Test PyMongoArrow on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python_version: ['3.6', '3.9']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.4
          mongodb-replica-set: test-rs
      - name: Install dependencies
        run: |
          python -m pip install -U pip wheel
          pip install .
        working-directory: ./bindings/python
      - name: Run test suite
        run: python setup.py test
        working-directory: ./bindings/python
