name: Test mongo-arrow

on:
  push:
  pull_request:

jobs:
  test:
    name: Test PyMongoArrow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.4
          mongodb-replica-set: test-rs
      - name: Install dependencies
        run: |
          python -m pip install -U pip wheel
          pip install .
        working-directory: ./bindings/python
      - name: Run test suite
        run: python setup.py test
        working-directory: ./bindings/python
